global class AccessibilityProjectBilling{
    
   public static void callBillingService(String projectId, Decimal billingAmount){
        //Setup username, password, billAmount, and projectid in BillingServiceProxy.project and then call billProject method

         //If response is ok set Accessibility Project Status = Complete
     String a = 'jay';
     String b = 'kumar';
     String c = a+b;
     System.debug('Full Name: '+c);
    }
}